const { Router } = require('express');
const categoriasRoutes = require('./categorias');
const produtosRoutes = require('./produtos');
const auditoriaRoutes = require('./auditoria');
const authRoutes = require('./auth');
const pesquisasRoutes = require('./pesquisas');
const calculoFreteRoutes = require('./calculofrete');
const cartRoutes = require('./cart');
const usuariosRoutes = require('./usuarios');
const pedidosRoutes = require('./pedidos');
const visitanteEventoRoutes = require('./visitanteEvento');
const kpiConfigRoutes = require('./kpiConfig');
const faturamentoCompletoRoutes = require('./faturamentoCompleto');
const leadtimeRoutes = require('./leadtime');
const dashboardRoutes = require('./dashboard');
const enderecosRoutes = require('./enderecos');
const avaliacoesRoutes = require('./avaliacoes');
const adminKpisRoutes = require('./adminKpis');
const analyticsRoutes = require('./analytics');

const router = Router();

router.use('/categorias', categoriasRoutes);
router.use('/produtos', produtosRoutes);
router.use('/auditoria', auditoriaRoutes);
router.use('/auth', authRoutes);
router.use('/pesquisas', pesquisasRoutes);
router.use('/frete', calculoFreteRoutes);
router.use('/cart', cartRoutes);
router.use('/usuarios', usuariosRoutes);
router.use('/pedidos', pedidosRoutes);
router.use('/visitante-evento', visitanteEventoRoutes);
router.use('/kpi-config', kpiConfigRoutes);
router.use('/avaliacoes', avaliacoesRoutes);
router.use('/admin/kpis', adminKpisRoutes);
router.use('/faturamento-completo', faturamentoCompletoRoutes);
router.use('/leadtime', leadtimeRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/enderecos', enderecosRoutes);
router.use('/analytics', analyticsRoutes);

module.exports = router;
